name: Vision Watcher

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install feedparser requests huggingface_hub
      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python vision_watcher.py
